spring: 
  cloud: 
    gateway: 
      discovery:
        locator: 
          enabled: true
          lowerCaseServiceId: true
  application: 
    name: server-gateway

server:
  port: 8082
  
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/